markdown: CommonMarkGhPages
permalink: pretty
production_url : http://JacobHelton57.github.io/Jekyll-Blog-Undiscovered
exclude: ['README.md']
paginate: 3
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Jacob Helton"
      banner_image: "900x300.png"
      thumbnail: "750x300.png"